### PR TITLE
Add act:* permission and whisper permission

### PR DESCRIPTION
**Pull request by JamyDev**
Needed for the backend part of limiting banned users.

### CODE REVIEW

**Comment by connor4312** [comment]
Going to hold off on merging this until the backend PR is in and finalized if that's alright :)

**Comment by JamyDev** [comment]
Yup preparing that now

**Comment by JamyDev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;40y3HGKr&#x2F;67-increase-restrictions-on-banned-users"> Increase Restrictions on banned Users</a>

**Comment by SimonSchick** [comment]
👍

**Pull request merged**
